FROM kongdeju/centos-dev:stable

MAINTAINER kongdeju <kongdeju@gene.ac>

RUN conda install -y perl && conda clean -y --all \
    && wget http://sleepycat.org/tech/perl/cpanm -O /usr/bin/cpanm && chmod +x /usr/bin/cpanm




