from kdj/alpine-dev

RUN conda install -y perl && conda install -y fastqc && conda install -y fastp && pip install mkdocs

RUN pip install -i http://pypi.douban.com/simple/ ngsqc --trusted-host pypi.douban.com

 
